engine:
  kind: modern_ebpf

rules_files:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml
  - /etc/falco/rules.d/devshield-rules.yaml

json_output: true
json_include_output_property: true
log_stderr: true
log_syslog: false
stdout_output:
  enabled: true
syslog_output:
  enabled: false
file_output:
  enabled: false
program_output:
  enabled: false
